### ISSUE TITLE
Some Genesis Sample strings still present after theme generation

### ISSUE THREAD

**Issue by nickcernis** [jayhill90/genesis-generator#24]
Great work on this, Jay!

I found a few Genesis Sample strings were present in a theme I generated with the command from your docs:

- `landing.php`: 'Genesis sample.' present in header.
- `notice-update.js`: `@package GenesisSample` in header.
- `phpcs.xml.dist`: `ruleset name="Genesis-Sample"`

**Comment by jayhill90** [comment]
Thanks @nickcernis I'll get this knocked out.

**Comment by jayhill90** [comment]
Just jotting down some notes here to come back to. 

Currently I use two arrays to contain the sample strings, and the replace strings. This is getting a bit unwieldy as we add more strings as they are required to be in a certain order. Granted these last three will be the last to be added, but there's probably a way to handle the variations of genesis-sample in a more concise manner.

We generate the Genesis Sample transformations in https://github.com/jayhill90/genesis-generator/blob/7542d200d16d4fe49dc158028c0274381571c8c6/inc/class-command.php#L107 and replace is an empty array until https://github.com/jayhill90/genesis-generator/blob/7542d200d16d4fe49dc158028c0274381571c8c6/inc/class-command.php#L79
